version: "3.7"
services:
  api:
    image: node:14-alpine
    container_name: api-typescript
    restart: always
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    command: yarn dev
